language: node_js
node_js:
  - "10.16.0"
script:
 - npm test
 - npm run build
 secure: "FrXIur2a6NaIL5+6aLS/6NJGmynLZxGN+KuV6jo6hvEBHkzYF1Bgy5CDJAVmmbwMYIyku2e0pmw1H1gCCdeVzD0HymxHwz+Ef2oxbfjMgolqL6d58+A3GzBZU3HJbv+KU8r0/EMdThlLu14t+ZZcC0vYMRYAzTf7wX8VkgiNZyjR5sg2IAmSwD/hvuPiwAFGdUhWA1jIXGR3Ul4rnQjeRCNjgcu8qRnDXeV/4e3Ptq7O8BSS3XYwBAcW3l+eHS406brKrGVClh65PqwmHc2jxs7Rca4LZ2PgkUfHEEXiG8cy4/EQZVmobgdUTppp6EIwibR7miIWvoOUJ7i51Xy5xo+wmgeTE9amCLauznJHXOSK3z4nllD2isCU6e7+CFgsebIgx9n7bBBOD90tXB3j3W6fSAdhWIhTh3mxfRje7Gc3X1f4cZiRY3/MZysbxH7P1WFFqnAUwHMH2j/7dgK7EzVffGmW6CTDcdeSvtl60GP1O8j4q6i87Fwo4P0VwTA3OmFq9UT/A9i5y20xQId1nZpZaqjLkLxnSESaU2eauiGGeiQtTJhMRK/e70xtmPUgxoSdMVTS+qNmzPq04qhyxZLPIV+kDbecOjHwvD6ZqlZjZfIfOzMMdprO/4HvXx3iUDWbYyp/U6l94/IUxhMOc3Ild3Rlhmq8dAJygxOagAY="
