language: node_js
node_js:
  - "10.16.0"
script:
 - npm test
 - npm run build
deploy:
  provider: firebase
  token:
    secure: GynYyp175tYsIsm11Yh8MfKvw3Gj68uaa9FJfP785ibYz4iRXhvwJvHffULH1/B/cA4IYyZYr+0vn2kZFETYDNpGdTZkQw1QRyXHNsYfn6DiOT7k/DzTngpt43/bc/rWi/+exVPevndzvcLlZhNE7WKjF1E9IUPToJ17NcmpLplfyP6Di/ZJ7Lx6UzyjfrVKTjrmf5R2jy7Heu3mGffrlGagGBavfPTbv3eWWENaD/5G9wwV6dF03mndWXwwuJdln1rtsaPnfWDDz11PjrOEtljFWFIiuevaa1c3jao3JKmrZjqWGUXEK+S1CuscDdyzY2D67dqv8aMwIPcsY2xP+J9RFkp8E2J7wiNRpdCcMuRfgWCGlEXQEJksz1KeO9B9aEQS3lrrxrifpzPE4C2WuknBEKnt6e8VaH+i4btX5SWIjlsX50g3o9jmrqmIiVi7co2wA1M6QArk/o7BzmsAeI+WXmwLvd/NzCdTglZuQ32K+LdonUAivWS1CVFUu7TkjH+GqNdST8Xfb00fd8AfjGudPh2nd35j9NVsxeFLmu6kVm6L5hBp/jlZky9E/Hb+OPvSMFBx7aNTDe0JB6lj+kM4MzfQaShHHlgX1CEkZXuFBWScD1FM+Ld7nsueIX4CzoZWjpwOVcUq4pR27JxiX0s5MKMe8Ui37e3oYgWniG0=
