language: node_js
node_js:
  - "10.16.0"
script:
 - npm test
 - npm run build
deploy:
  provider: firebase
  token:
    secure: "naHNifysfYYhfDIb8GcRgfPPca1NQ3uyVTmJUz6bf2/01gmvwbsSoLn+nLXwPA0FgvJCApcbH5cEueVGYfJDuFSzGjyiiTRlA2SZOcxd6a7dLC9GXXNmxk3IRcdoUnSX4QmBQO1fSi4yngFEv60VDQeoCRCBqik1dnkNlabEx3sXGl6XVD9lUw8ERtvNJYzmvKr8fqMdXQlnyddsoZxu+q+F7g6hBHBCg6b29e5c0r4ztKjd0xyXmS6q16oqy97FUeRkJzZgH/RXRSkox2euacANFxs6x+zwGFBXcC1ZW1gBLwMmb7/XUriv65m0k5icdeo/XwJb8W8qu2Kn46V+wiVFOW5I+lLfJZNqU5tV8UVxYLbNCylEVERZKA9oODIGF8T/2L1y38KrVTwF4TMYE7mO75MsrHhweov5B1MTeJuNZG0/Ym28d6H20F2bJkDMWRKMowhrJ0gk8appdwDWJ2kEGJLOdO4XFI56XxF8CKyG83tR+Tl7hoTUfWK9DZjw3e3sCACBVOw0WAIL2ux2TWh/LFrzD51yGj7BdNNXTqJj3yzd7Aw6iM9Bjb132daxRY4WQl1ZK8SDlrEIWqU2KfQ/A/cfm0BVW0O4QU/M61iyNhRGmurBWroe/53cciX2YHhO2wCdRLhCmnXDCUMS2sf/rKP1kPXppwfWb8DPN90="
    